### ISSUE TITLE
您好，我是github上vue-activiti-demo工作流仓库的创建人，由于项目中涉及公司信息，现公司要求删除，麻烦您将您fork的这个仓库删除，非常感谢，祝您工作愉快。

### ISSUE THREAD

**Issue by griabcrh** [Coder-ZJQ/RxSwift#1]
您好，我是github上vue-activiti-demo工作流仓库的创建人，由于项目中涉及公司信息，现公司要求删除，麻烦您将您fork的这个仓库删除，非常感谢，祝您工作愉快。

**Comment by Coder-ZJQ** [comment]
你好，已删除 [Coder-ZJQ/vue-activiti-demo](https://github.com/Coder-ZJQ/vue-activiti-demo)

**Comment by griabcrh** [comment]
好的，感谢您的支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Coder-ZJQ/RxSwift"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Coder-ZJQ/RxSwift] 您好，我是github上vue-activiti-demo工作流仓库的创建人，由于项目中涉及公司信息，现公司要求删除，麻烦您将您fork的这个仓库删除，非常感谢，祝您工作愉快。 (#1)





 
你好，已删除 Coder-ZJQ/vue-activiti-demo
